# Generated by Django 2.1 on 2020-01-10 00:07

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20200109_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
