# Generated by Django 2.1 on 2020-01-15 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20200110_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='poster',
        ),
    ]
